### ISSUE TITLE
Can't reach sharelocation page when connecting from other hosts

### ISSUE THREAD

**Issue by wickywaka** [babatech/ASP#1]
I run the program on my PC and On my PC I can go to sharelocation page when I click on sharelocation from homepage.
But When I open the homepage from other computer by typing the IP of my PC and port number, and after that when I click on sharelocation link, it tries to go localhost:3000/sharelocation instead of my_PC_IP:3000/sharelocation

I can access the sharelocation page by typing my_PC_IP:3000/sharelocation from other computer.

**Comment by shahabshakoor** [comment]
This is a server side problem, (Permission).
This link has master deployment.
http://asp-fh-kiel.azurewebsites.net/

one solution for this problem is to use two different browser for testing. when both browser works with share location. let me know before push to master. in my last master push i change some file structure in project
